/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sorts;

import java.util.Arrays;

public class sorts {

    public static void insertionSort(int[] inArr) {

        // Iterate through the input array from index length-1 to index 1
        for (int i = 0; i < inArr.length; i++) {
            int cur = inArr[i];
            // Iterate through all elements to the left of the current index.
            int j = i - 1;
            while (j >= 0 && cur < inArr[j]) {
                // While the current is less than the element to it's left, keep moving.
                inArr[j + 1] = inArr[j];
                j--;
            }
            inArr[j + 1] = cur;
        }
    }

    public static void mergeSort(int[] inArr) {
        if(inArr.length > 1) {
            int mid = (int)Math.floor(inArr.length/2);
            int[] leftSide = Arrays.copyOfRange(inArr,0, mid);
            int[] rightSide = Arrays.copyOfRange(inArr, mid, inArr.length);

            mergeSort(leftSide);
            mergeSort(rightSide);
            merge(leftSide, rightSide, inArr);
        }
    }

    public static void merge(int[] l, int[] r, int[] inArr) {
        int i = 0, j = 0, k = 0;
        while(i < l.length && j < r.length && k < inArr.length) {
            if(l[i] < r[j]) {
                inArr[k] = l[i];
                i++;
            }
            else {
                inArr[k] = r[j];
                j++;
            }
            k++;
        }
        // Place remaining left side elements.
        while(i < l.length){
            inArr[k] = l[i];
            i++;
            k++;
        }
        // Place remaining left side elements.
        while(j < r.length){
            inArr[k] = r[j];
            j++;
            k++;
        }
    }

}
